openapi: 3.0.0
servers:
  - url: https://spxon.getid.dev/
    description: Production server
  - url: https://spxon.sb.getid.dev/
    description: Sandbox server
info: 
  title: Enveloped Application
  version: '2.0'
  x-logo:
    url: './logo.svg'
    altText: GetID
  
  description: |
    
    # API 
    Information about API

    # SDK
    Information about API

paths:
  /plugins/v1/acceptor/application:
    post:
      security:
        - ApiKeyAuth: []
      description: Allows to send data to verification
      requestBody:
        content:
          'application/json':
            schema:
              properties:
                envelopedApplication:
                  $ref: '#/components/schemas/EnvelopedApplication'
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                properties:
                  responseCode:
                    value: 200
                    example: 200
                    type: integer
                  id:
                    type: string
                    format: ObjectId
                    example: 5e62110968e3fb4d655756d1
        '401':
          description: error, missing or wrong authorization headers
          content:
            'application/json':
              schema:
                properties:
                  responseCode:
                    value: 401
                    example: 401
                    type: integer
                  errorMessage:
                    type: string
                    example: 'Unauthorized'
        '402':
          description: error, wrong format or missing data
          content:
            'application/json':
              schema:
                properties:
                  responseCode:
                    value: 402
                    example: 402
                    type: integer
        '400':
          description: error, empty request body
          content:
            'application/json':
              schema:
                properties:
                  responseCode:
                    value: 400
                    example: 400
                    type: integer
  /plugins/v1/acceptor/application/{id}:
    get:
      security:
        - bearerAuth: []
      description: Allows to get verifired application
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                allOf:
                  - type: object
                    properties:
                      responseCode:
                        type: integer
                      id:
                        type: string
                  - $ref: '#/components/schemas/VerificationResult'
                  
        '401':
          description: error, missing or wrong authorization headers
          content:
            'application/json':
              schema:
                properties:
                  responseCode:
                    type: integer
                  errorMessage:
                    type: string
                    example: 'Unauthorized'
        '402':
          description: error, Bad data. Application with Id {id} not found
          content:
            'application/json':
              schema:
                properties:
                  responseCode:
                    type: integer
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: |
        You can find token on settings page.
        It's header is required foa all API methods
  schemas:
    EnvelopedApplication:
      type: object
      properties:
        metadata:
          $ref: '#/components/schemas/SourceMetadata'
        #extensions:
        #  $ref: '#/components/schemas/Extensions'
        application:
          $ref: '#/components/schemas/Application'
        verificationTypes:
          $ref: '#/components/schemas/VerificationTypes'
    VerificationResult:
      allOf:
        - $ref: '#/components/schemas/EnvelopedApplication'
        - type: object
          properties:
            processStatus: 
              $ref: '#/components/schemas/ProcessStatus'
            overallResult:
              $ref: '#/components/schemas/OverallResult'
            servicesResults:
              $ref: '#/components/schemas/ServiceResults'
        
        
    Application: 
      type: object
      properties:
        customerId:
          nullable: true
          type: string
          description: Use this field to save custom ID from you system
          example: "go-1984"
        fields:
          type: array
          description: |
            Array of data which you would like check.
            For example: it will be data from web form with last name and date of birth
          nullable: true
          items: 
            $ref: '#/components/schemas/Field'
          example: 
            - contentType: string
              content: Firs Name
              category: Artem
              requireCheck: true
            - contentType: string
              content: Last Name
              category: Gerus
              requireCheck: true
            - contentType: sex
              content: male
              category: sex
        documents:
          type: array
          nullable: true
          description: list of document for data extracting or crosschecking
          items:
            type: object
            properties:
              issuingCountry:
                type: string
                description: Country code of country of issue
                format: 'ISO 3166'
                example: UK
              documentType:
                $ref:  '#/components/schemas/DocumentType'
              files:
                description: document photos or scans 
                type: array
                items: 
                  $ref: '#/components/schemas/DocumentMedia'
            required:
              - images
              # mrz:
              #   type: string
              # nfc:
              #   type: array
              #   items:
              #     $ref: '#/components/schemas/Field'
          required: [images]
        selfie:
          properties:
            files:
              type: array
              description: list of selfie for face-matching
              items:
                $ref: '#/components/schemas/FacesMedia'
          require:
            - files
    
    Field:
      type: object
      oneOf:
        - $ref: '#/components/schemas/StringField'
        - $ref: '#/components/schemas/DateField'
        - $ref: '#/components/schemas/SexField'
        - $ref: '#/components/schemas/BoolField'
        - $ref: '#/components/schemas/CountryField'
        - $ref: '#/components/schemas/NumberField'
          
        
    
    FiledBase: 
      type: object
      properties:
        category:
          type: string
          description: |
            Kind of data. For example: first name, last name...
        requireCheck:
          nullable: true
          default: false
          type: boolean
          description: |
            Check of data is required.
            If this flag is true and we could not check this data from document,
            application status is going to decline 
          example: true
    
    StringField:
      type: object
      allOf:
        - type: object
          properties:
            contentType:
              type: string
              enum: [string]
            content:
              type: string
              description: The value of field
        - $ref: '#/components/schemas/FiledBase'
      required: [content, category, contentType]
    
    DateField:
      type: object
      allOf:
        - type: object
          properties:
            contentType:
              type: string
              enum: [date]
            content:
              format: date
              type: string
              description: The value with date
        - $ref: '#/components/schemas/FiledBase'
      required: [content, category, contentType]
    
    SexField:
      type: object
      allOf:
        - type: object
          properties:
            contentType:
              type: string
              enum: [sex]
            content:
              enum: [male, female]
              type: string
              description: male or female
        - $ref: '#/components/schemas/FiledBase'
      required: [content, category, contentType]
    
    NumberField:
      type: object
      allOf:
        - type: object
          properties:
            contentType:
              type: string
              enum: [number]
            content:
              format: number
              type: string
              description: The number value
        - $ref: '#/components/schemas/FiledBase'
      required: [content, category, contentType]

    CountryField:
      type: object
      allOf:
        - type: object
          properties:
            contentType:
              type: string
              enum: [country]
            content:
              format: 'ISO 3166'
              type: string
              example: US
              description: Country code
        - $ref: '#/components/schemas/FiledBase'
      required: [content, category, contentType]

    BoolField:
      type: object
      allOf:
        - type: object
          properties:
            contentType:
              type: string
              enum: [bool]
            content:
              enum:
                - true
                - false
              type: string
              example: true
              description: The bool value
        - $ref: '#/components/schemas/FiledBase'
      required: [content, category, contentType]

  
    FacesMedia:
      type: object
      properties:
        mediaType:
          type: string
          description: media-type of content
          example: image/png
        url:
          description: address from which we can download or blob
          type: string
          example: "data:image/png;base64,R0lGODlhDAAMAK..."
      required: [mediaType, kind, url]
    
    DocumentMedia:
      type: object
      properties:
        mediaType:
          type: string
          description: media-type of content
          example: image/png
        kind:
          type: string
          description: kind of document page
          enum:
            - front
            - back
            - page
          example: front
        url:
          description: address from which we can download or blob
          type: string
          example: "data:image/png;base64,R0lGODlhDAAMAK..."
      required: [mediaType, kind, url]

    Extensions:
      type: array
      items: 
        type: object
        properties:
          extension:
            type: string
            example: my extension
          extensionData:
            type: string
            # example: {substructure}
            description: contains substructure in JSON
        required: [extension, extensionData]

    OverallResult:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/VerificationStatus'
        identifierComment:
          type: string
        validationDate:
          type: string
          format: date-time
      additionalProperties: false
      required:
        - status
    VerificationStatus:
      type: string
      enum:
        - declined
        - approved
        - processing
        - review-needed
    ProcessStatus:
      type: string
      enum:
        - done
        - processing
        - review-needed
    SourceMetadata:
      nullable: true
      type: object
      description: |
        The meta information about source of the input data.
        You can use that field to send the custom meta information between request and response.
        We are going to add this data into response object as is.
        Max count of fields is 30
      maxProperties: 30
      properties:
        # createDate:
        #   description: date and time of creating application
        #   type: string
        #   format: date-time
        #   example:
        #     - "2020-03-17T20:28:37.061Z"
        # ipAddress:
        #   type: string
        platform:
          type: string
          description: The version of os where was created an application
          example:
            - android
            - ios
            - web
        createDate:
          type: string
          description: Date and time of creating application
          format: date-time
          example: "2020-03-17T20:28:37.061Z"
        
        appName:
          type: string
          description: The name of application which is doing request
          example: my-api-client
        appVersion:
          type: string
          description: The version of application which is doing request
          example: 1.0.0
        locale:
          type: string
          description: The locale of application which is doing request
          format: locale
          example: en_US
      additionalProperties:
        x-additionalPropertiesName: x-
        description: You can add custom headers with prefix `x-`
        type: string
      example:
        platform: android
        locale: en_US
        createDate: "2020-03-17T20:28:37.061Z"
        appName: my-api-client
        appVersion: 1.0.0
        x-my-custom-meta-name-1: custom-value-1
        x-my-custom-meta-name-2: custom-value-2

    ServiceResults:
      type: object
      properties:
        faceMatching:
          type: array
          items:
            $ref: '#/components/schemas/FaceMatching'
        liveness:
          type: array
          items:
            $ref: '#/components/schemas/Liveness'
        dataExtraction:
          type: array
          items:
            $ref: '#/components/schemas/DataExtraction'
        crossChecking:
          type: array
          items:
            $ref: '#/components/schemas/CrossChecking'
        watchlists:
          type: array
          items:
            $ref: '#/components/schemas/Watchlists'
      additionalProperties: false
    FaceMatching:
      type: object
      properties:
        identifierComment:
          type: string
        verifier:
          type: string
        status:
          $ref: '#/components/schemas/VerificationStatus'
        processStatus:
          $ref: '#/components/schemas/ProcessStatus'
        results:
          type: array
          items:
            $ref: '#/components/schemas/FaceMatchingResult'
      required:
        - status
      additionalProperties: false
    FaceMatchingResult:
      type: object
      properties:
        contentType:
          $ref: '#/components/schemas/ContentType'
        category:
          type: string
        content:
          type: string
      required:
        - contentType
        - category
        - content
      additionalProperties: false
    Liveness:
      type: object
      properties:
        identifierComment:
          type: string
        verifier:
          type: string
        status:
          $ref: '#/components/schemas/VerificationStatus'
        results:
          type: array
          items:
            $ref: '#/components/schemas/LivenessResult'
        processStatus:
          $ref: '#/components/schemas/ProcessStatus'
      required:
        - status
      additionalProperties: false
    LivenessResult:
      type: object
    DataExtraction:
      type: object
      properties:
        identifierComment:
          type: string
        verifier:
          type: string
        status:
          $ref: '#/components/schemas/VerificationStatus'
        results:
          type: array
          items:
            $ref: '#/components/schemas/DataExtractionResult'
        processStatus:
          $ref: '#/components/schemas/ProcessStatus'
      required:
        - status
      additionalProperties: false
    DataExtractionResult:
      type: object
      properties:
        contentType:
          $ref: '#/components/schemas/ContentType'
        category:
          type: string
          example:
            - First name
            - Last name
            - Date of Birth
        content:
          type: string
      required:
        - contentType
        - category
        - content
      additionalProperties: false
    CrossChecking:
      type: object
      properties:
        identifierComment:
          type: string
        verifier:
          type: string
        status:
          $ref: '#/components/schemas/VerificationStatus'
        results:
          type: array
          items:
            $ref: '#/components/schemas/CrossCheckingResult'
        processStatus:
          $ref: '#/components/schemas/ProcessStatus'
      required:
        - status
      additionalProperties: false
    CrossCheckingResult:
      type: object
      properties:
        category:
          type: string
          example:
            - First name
            - Last name
            - Date of Birth
        form:
          type: string
        extracted:
          type: string
      required:
        - category
        - form
        - extracted
      additionalProperties: false
    Watchlists:
      type: object
      properties:
        identifierComment:
          type: string
        verifier:
          type: string
        status:
          $ref: '#/components/schemas/VerificationStatus'
        results:
          type: array
          items:
            $ref: '#/components/schemas/WatchlistsResult'
        processStatus:
          $ref: '#/components/schemas/ProcessStatus'
      required:
        - status
      additionalProperties: false
    WatchlistsResult:
      type: object
      properties:
        contentType:
          $ref: '#/components/schemas/ContentType'
        category:
          type: string
        content:
          type: string
      required:
        - contentType
        - category
        - content
      additionalProperties: false
    ContentType:
      type: string
      enum:
        - string
        - number
        - sex
        - date
        - country
        - boolean
    
    VerificationTypes:
      type: array
      description: |
        It's list of verification which you want to do:
        * watchlists - It's check user on PEPs. You can fill fields (first name, last name)
        * face-matching - We will try check photo on document and selfie. You can fill selfie list and document list
        * extract-data - We will try extract data from documents. You can fill documents
        * crosschecking - You send information about user and we will check a conformity between it and extracted data
        If you don't send this field we do all verification what we can. You can fill documents and fields
      items:
        nullable: true
        type: string
        enum: ['watchlists', 'face-matching', 'extract-data', 'crosschecking']
      example:
         ['watchlists', 'face-matching', 'extract-data']

    DocumentType:
      type: string
      description: kind of document
      enum:
        - passport
        - id-card
        - driving-licence
        - residence-permit
      example: id-card
